#!/bin/bash -
# -*- coding: UTF8 -*-

#===============================================================================
#
#          FILE: ScriptGeneratePbfFile.sh
#
#         USAGE: ./ScriptGeneratePbfFile.sh
#
#   DESCRIPTION: see README.md
#
#       OPTIONS: ---
#  REQUIREMENTS: ---
#          BUGS: ---
#         NOTES: ---
#        AUTHOR: https://github.com/JulioJu
#  ORGANIZATION:
#       CREATED: 01/29/2019 11:01
#      REVISION:  ---
#===============================================================================


trap 'kill' HUP
trap 'kill' INT
trap 'kill' QUIT
trap 'finishError "$LINENO"' ERR
trap 'finish' EXIT
# Cannot be trapped
# trap 'kill' KILL
trap 'kill' TERM

# set -euET
set -euET
# Note: `set +E' doesn't work
# set -x

close() {
    # "_" is the throwaway variable
    # sleep 2
    if [[ -n "${filePbfBasename+x}" ]] && [[ -e "${filePbfBasename}" ]]
    then
        echo -e "\n\n ${URED} Info: ${NC}" \
            "The fat size file '${filePbfBasename}' could be deleted." \
            "\n\n"
    fi
    read -r -t 1 -n 10000 _ || echo ""
    read -r -p "Press 'ENTER' to close"
}

kill() {
    set +x
    1>&2 echo -e "\\n\\n\\n""${URED}""Killed by user""${NC}""\\n\\n"
    exit 130
}

finishError() {
    set +x
    1>&2 echo "In the script, error on line: '$1'"
    exit 2
    # Otherwise, all script it's executed
}

finish() {
    returnCode=$?

    set +x
    if [[ "${returnCode}" -gt 0 ]] ; then
        1>&2 echo -e "\\n\\n\\n${URED}ERROR" \
            "with code '${returnCode}'${NC}\\n\\n"
        close
    else
        echo -e "\\n\\n\\n""${URED}""SUCCESS""${NC}""\\n\\n"
        close
    fi
    echo -e "\n\n\n"
}

error() {
    set +x
    1>&2 echo -e "\\n\\n\\n${URED}ERROR:" "${@:2}" "${NC}\\n\\n"
    exit "${@:1:1}"
}

usage() {
    error 5 "${NC}Should have one arguments." \
        "\n\t* First one: name of the country to build" + \
            "(e.g. europe-latest, europe/france-latest" + \
            " or europe/france/rhone-alpes-latest ).\n" \
        "\n\tNote: build relative to the path where the scritp is launched." \
        "\n\tNote2: should be used with ArchLinux Package, otherwise" \
            "location of profile.lua file could not be the same and the" \
            "script will fail."
}

testCommandLine(){
    if [[ $# -ne 1 ]]
    then
        usage
    fi
}

convertBitToGB() {
    local -n sizeGB="${1}"
    # shellcheck disable=SC2034
    sizeGB=$(awk '{ byte =$1 /1024/1024/1024; print byte " GB" }' <<< "${2}")
}

testsBeforeStart() {
    local sizeLine
    local -r curlSizePatern="Content-Length"

    # note tat `wget' return with error code when error 404
    if sizeLine=$(grep "^${curlSizePatern}" < \
        <(curl --head --fail "$urlFileToDownload"))
    then
        :
    else
        error 5 "Fail to download page with URL '${urlFileToDownload}'."
    fi

    sizeLine=${sizeLine/"$curlSizePatern: "/}
    local -ri sizeFileToDownload=${sizeLine//[$'\t\r\n']}
    local -i sizeNeeded
    sizeNeeded=$(awk '{ size=$1 * 10 ; print size }' \
        <<< "${sizeFileToDownload}")

    local -i sizeLocalFileSystemAvailable
    sizeLocalFileSystemAvailable=$(awk '{print $4}' < <(tail -n 1 < \
        <(df --block-size=1 .)))

    local sizeFileToDownloadGB
    convertBitToGB sizeFileToDownloadGB "${sizeFileToDownload}"
    local sizeNeededGB
    convertBitToGB sizeNeededGB "${sizeNeeded}"
    local sizeLocalFileSystemAvailableGB
    convertBitToGB sizeLocalFileSystemAvailableGB \
            "${sizeLocalFileSystemAvailable}"

    local -ar echoDiskSpace=("\n\tFile to download at ${urlFileToDownload}:" \
                " ${sizeFileToDownloadGB}" \
            "\n\tFile generated by the script: maybe around ${sizeNeededGB}" \
            "\n\tDisk space in the current file system: " \
                "${sizeLocalFileSystemAvailableGB}")
    if [[ ${sizeNeeded} -lt $sizeLocalFileSystemAvailable ]]
    then
        echo -e "So cool, enough disk space ${echoDiskSpace[*]}"
    else
        error 6 "Not enough disk space. ${echoDiskSpace[*]}"
    fi
}

buildProfile() {
    local -r profile=${1}
    local -r dirProfile="${DIR_WORKING}/${country}-${profile}"
    local -r fileOsrm="${country}.osrm"

    mkdir "${dirProfile}"
    mv "${filePbfBasename}" "${dirProfile}"

    pushd "$dirProfile"

    osrm-extract "${filePbfBasename}" -p "/usr/share/osrm/profiles/${profile}.lua"
    osrm-partition "${fileOsrm}"
    osrm-customize "${fileOsrm}"
    osrm-routed --algorithm=MLD "${fileOsrm}"

    mv "${filePbfBasename}" ../

    popd
}

main() {
    set -x

    local -r fileToDownload="${1}.osm.pbf"

    local -r urlFileToDownload="https://download.geofabrik.de/${fileToDownload}"

    local country
    country="$(basename "${1}")"

    local filePbfBasename
    filePbfBasename="$(basename "${1}").osm.pbf"

    DIR_WORKING="$(pwd)/osrm-${country}"

    set +x
    testsBeforeStart
    set -x

    mkdir "${DIR_WORKING}"
    cd "${DIR_WORKING}"

    wget "${urlFileToDownload}"
    wget "${urlFileToDownload}.md5"
    md5sum -c "${filePbfBasename}.md5"

    buildProfile bicycle
    buildProfile foot
    buildProfile car
}

echo -e "\n\nStart of Script\n============\n"

# shellcheck disable=SC2154
export PS4='${debian_chroot:+($debian_chroot)}'\
'\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\] [\D{%T}] \$ '
# declare -g -r PS4Light="\\033[1;32m""$USER@""$HOSTNAME""\\033[0m"": "

echo -e "Build relative to the path where the script is launched.\n\n"
declare -g DIR_WORKING
# DIR_WORKING="$(pwd)"
# DIR_WORKING="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd -P)"
# cd "${DIR_WORKING}"

declare -g -r URED="\\033[4;31m"
declare -g -r NC="\\033[0m"

testCommandLine "${@}"

main "${@}"
